import puppeteer from 'puppeteer-core';
const b = await puppeteer.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
const p = await b.newPage();
await p.setViewport({ width: 1700, height: 950 });
const errs = []; p.on('pageerror', (e) => errs.push(e.message));
await p.goto('http://localhost:5175/?ex=ejercicio-11.json', { waitUntil: 'networkidle0' });
const vb = () => p.$eval('.canvas svg', (s) => s.getAttribute('viewBox'));
const dis = () => p.$eval('.scene header button', (b) => b.disabled);
const v0 = await vb();
console.log('inicial', v0, 'encuadrar deshabilitado:', await dis());
const box = await (await p.$('.canvas svg')).boundingBox();
await p.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
await p.mouse.wheel({ deltaY: -600 });
await new Promise((r) => setTimeout(r, 200));
const v1 = await vb(); console.log('zoom', v1, v1 !== v0);
await p.mouse.move(box.x + 300, box.y + 300); await p.mouse.down(); await p.mouse.move(box.x + 380, box.y + 340, { steps: 5 }); await p.mouse.up();
const v2 = await vb(); console.log('pan', v2, v2 !== v1);
await p.screenshot({ path: process.argv[2] });
await p.click('.scene header button');
const v3 = await vb(); console.log('encuadrar', v3 === v0);
console.log('errores:', errs.length);
await b.close();
