import { bernstein, curvatureFrame, derivative, evaluate, powerCoefficients, arcLengthTable } from '../math/bezier.js';
import { initialScene, builtInExamples } from '../model/examples.js';
import { createScene, hydrateScene, makeId } from '../model/defaults.js';
import { createStore, addDraftPoint, activeChain, applyConstraints, deleteSelection, dependentPointIds, elevateSelected, fitBounds, freezeSelected, pointMap, pointsFor, selectedSegment, splitSelected } from '../model/store.js';
import { validateScene } from '../model/validation.js';
import { joinsFor, screenToWorld, SvgSceneRenderer, worldToScreen } from '../render/svgScene.js';
import { Pane } from 'tweakpane';
import katex from 'katex';

const TOOLS = { select: ['V', 'Seleccionar'], add: ['A', 'Agregar'], delete: ['D', 'Borrar'], explore: ['E', 'Explorar'], pan: ['H', 'Desplazar'] };
const SVG_NS = 'http://www.w3.org/2000/svg';
const isEditing = () => ['INPUT', 'TEXTAREA', 'SELECT'].includes(document.activeElement?.tagName) || document.activeElement?.isContentEditable;
const parseNumber = (value) => Number(String(value).replace(',', '.'));
const safeName = (name) => name.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-zA-Z0-9_-]+/g, '-').replace(/^-|-$/g, '').toLowerCase() || 'escena';
const expectedText = (expected) => {
  if (typeof expected === 'string') return expected;
  if (!expected || typeof expected !== 'object') return '';
  return Object.entries(expected).map(([key, value]) => `${key.toUpperCase()}: ${value === true ? 'cumple' : value === false ? 'no cumple' : String(value)}`).join(' · ');
};

export class BezierLab {
  constructor(root) {
    this.root = root; this.store = createStore(this.restoreSession() || initialScene()); this.tool = 'select'; this.activeTab = 'controls'; this.pointer = null; this.playing = false; this.lastFrame = 0; this.autosaveTimer = 0; this.examples = builtInExamples(); this.panelOpen = false;
    this.buildShell();
    this.renderer = new SvgSceneRenderer(this.svg, { onPointPointer: (e, id) => this.pointPointer(e, id), onSegmentPointer: (e, id) => this.segmentPointer(e, id) });
  }

  start() {
    this.bindShell();
    this.unsubscribe = this.store.subscribe((scene, status) => { this.scene = scene; this.render(status); this.scheduleAutosave(); });
    this.resizeObserver = new ResizeObserver(() => { const r = this.viewport.getBoundingClientRect(); this.renderer.setSize(r.width, r.height); this.render(this.store.status()); }); this.resizeObserver.observe(this.viewport);
    requestAnimationFrame((time) => this.tick(time));
  }

  buildShell() {
    this.root.innerHTML = `<main class="lab" aria-label="Laboratorio de curvas Bézier">
      <header class="topbar"><div class="brand"><span class="brand-mark">B</span><span>Laboratorio Bézier</span></div>
        <button data-command="new" class="command-button hide-small" title="Nueva escena">Nueva</button><button data-command="open" class="command-button hide-small" title="Abrir escena JSON">Abrir</button><button data-command="save" class="command-button hide-small" title="Guardar escena JSON">Guardar</button>
        <select data-role="examples" aria-label="Ejemplos incorporados" title="Ejemplos incorporados"></select>
        <button data-command="undo" class="tool-button" title="Deshacer (Ctrl+Z)" aria-label="Deshacer">↶</button><button data-command="redo" class="tool-button" title="Rehacer (Ctrl+Y)" aria-label="Rehacer">↷</button>
        <button data-command="fit" class="tool-button" title="Encuadrar todo (F)" aria-label="Encuadrar todo">⌗</button><span class="spacer"></span><button data-command="palette" class="tool-button" title="Paleta de comandos (Ctrl+K)" aria-label="Paleta de comandos">⌘</button><button data-command="illustration" class="command-button hide-small" title="Modo ilustración (Tab)">Ilustración</button><button data-command="export" class="command-button primary">Exportar</button><button data-command="panel" class="tool-button mobile-panel-button" aria-label="Abrir panel">☰</button>
      </header>
      <nav class="leftbar" aria-label="Herramientas"></nav>
      <section class="viewport-wrap"><svg class="viewport" tabindex="0" aria-label="Plano cartesiano interactivo"></svg><div class="welcome">Arrastrá los puntos o cargá un ejemplo <button aria-label="Cerrar mensaje">×</button></div><button class="info-button" aria-label="Abrir panel matemático">i</button><div class="zoom-controls"><button data-zoom="out" aria-label="Alejar">−</button><button data-zoom="in" aria-label="Acercar">+</button></div><aside class="math-panel" aria-label="Panel matemático"><div class="math-head"><strong>Panel matemático</strong><button aria-label="Cerrar panel">×</button></div><div class="math-content"></div></aside></section>
      <aside class="right-panel"><nav class="panel-tabs" aria-label="Paneles"><button data-tab="controls">Controles</button><button data-tab="bases">Bases</button><button data-tab="continuity">Continuidad</button><button data-tab="measurements">Mediciones</button></nav><div class="panel-body"></div></aside>
      <footer class="timeline"><select data-role="chain" aria-label="Cadena activa"></select><select class="segment-select" data-role="segment" aria-label="Tramo activo"></select><div class="scope-switch"><button data-scope="local">Local</button><button data-scope="global">Global</button></div><input class="play-slider" data-role="u-range" type="range" min="0" max="1" step="0.001" aria-label="Parámetro u"><input class="u-input" data-role="u-number" type="number" min="0" max="1" step="0.0001" aria-label="Valor de u"><div class="transport"><button data-command="restart" aria-label="Reiniciar">■</button><button data-command="play" aria-label="Reproducir o pausar">▶</button><button data-command="probe" aria-label="Fijar evaluación" title="Fijar evaluación">◆</button></div></footer>
      <div class="statusbar"><span data-status="tool"></span><span data-status="coords">x — · y —</span><span data-status="count"></span><span data-status="autosave">Autosave listo</span></div>
      <input data-role="file" type="file" accept="application/json,.json" hidden>
    </main>`;
    this.lab = this.root.querySelector('.lab'); this.svg = this.root.querySelector('.viewport'); this.viewport = this.root.querySelector('.viewport-wrap'); this.panel = this.root.querySelector('.right-panel'); this.panelBody = this.root.querySelector('.panel-body'); this.fileInput = this.root.querySelector('[data-role=file]');
    const nav = this.root.querySelector('.leftbar'); Object.entries(TOOLS).forEach(([id, [key, label]]) => { const b = document.createElement('button'); b.dataset.tool = id; b.textContent = key; b.title = `${label} (${key})`; b.setAttribute('aria-label', label); nav.append(b); });
    const select = this.root.querySelector('[data-role=examples]'); const placeholder = new Option('Ejemplos…', ''); select.add(placeholder); this.examples.forEach((ex) => select.add(new Option(`${ex.id.slice(0, 2)} · ${ex.title}`, ex.id))); select.add(new Option('Descargar catálogo completo…', '__download'));
  }

  bindShell() {
    this.root.addEventListener('click', (e) => { const command = e.target.closest('[data-command]')?.dataset.command; if (command) this.command(command); const tool = e.target.closest('[data-tool]')?.dataset.tool; if (tool) this.setTool(tool); const tab = e.target.closest('[data-tab]')?.dataset.tab; if (tab) { this.activeTab = tab; this.renderPanel(); } const scope = e.target.closest('[data-scope]')?.dataset.scope; if (scope) this.updatePlayhead('scope', scope, false); });
    this.root.querySelector('.welcome button').addEventListener('click', (e) => e.currentTarget.parentElement.remove());
    this.root.querySelector('.info-button').addEventListener('click', () => this.toggleMath()); this.root.querySelector('.math-head button').addEventListener('click', () => this.toggleMath(false));
    this.root.querySelectorAll('[data-zoom]').forEach((b) => b.addEventListener('click', () => this.zoom(b.dataset.zoom === 'in' ? 1.25 : .8)));
    this.root.querySelector('[data-role=examples]').addEventListener('change', (e) => { if (e.target.value === '__download') this.downloadCatalog(); else if (e.target.value) this.openExample(e.target.value); e.target.value = ''; });
    this.root.querySelector('[data-role=chain]').addEventListener('change', (e) => this.store.transact('Cambiar cadena', (s) => { s.presentation.selection.chainId = e.target.value; const c = activeChain(s); s.presentation.selection.segmentId = c.segmentIds[0] || null; s.presentation.playhead.segmentId = c.segmentIds[0] || null; s.presentation.playhead.chainId = c.id; }));
    this.root.querySelector('[data-role=segment]').addEventListener('change', (e) => this.selectSegment(e.target.value));
    const updatePosition = (value) => this.setTimelineValue(parseNumber(value)); this.root.querySelector('[data-role=u-range]').addEventListener('input', (e) => updatePosition(e.target.value)); this.root.querySelector('[data-role=u-number]').addEventListener('change', (e) => updatePosition(e.target.value));
    this.fileInput.addEventListener('change', (e) => this.importFile(e.target.files[0]));
    this.svg.addEventListener('wheel', (e) => this.wheel(e), { passive: false }); this.svg.addEventListener('pointerdown', (e) => this.backgroundPointer(e)); this.svg.addEventListener('pointermove', (e) => this.pointerMove(e)); this.svg.addEventListener('pointerup', (e) => this.pointerUp(e)); this.svg.addEventListener('pointercancel', (e) => this.pointerUp(e));
    window.addEventListener('keydown', (e) => this.keydown(e)); document.addEventListener('visibilitychange', () => { if (document.hidden) this.playing = false; });
  }

  render(status = this.store.status()) {
    if (!this.renderer || !this.scene) return; const rect = this.viewport.getBoundingClientRect(); this.renderer.setSize(rect.width, rect.height); this.renderer.render(this.scene); this.svg.className.baseVal = `viewport tool-${this.tool}`;
    this.root.querySelectorAll('[data-tool]').forEach((b) => b.classList.toggle('active', b.dataset.tool === this.tool)); this.root.querySelectorAll('[data-tab]').forEach((b) => b.classList.toggle('active', b.dataset.tab === this.activeTab)); this.root.querySelectorAll('[data-scope]').forEach((b) => b.classList.toggle('active', b.dataset.scope === this.scene.presentation.playhead.scope));
    this.root.querySelector('[data-command=undo]').disabled = !status.canUndo; this.root.querySelector('[data-command=redo]').disabled = !status.canRedo;
    this.renderSelectors(); this.renderPanel(); this.renderMath();
    this.root.querySelector('[data-status=tool]').textContent = `Herramienta: ${TOOLS[this.tool][1]}`; this.root.querySelector('[data-status=count]').textContent = `${this.scene.geometry.segments.length} tramos · ${this.scene.geometry.drafts.length} borradores`; this.root.querySelector('[data-status=autosave]').textContent = status.dirty ? 'Cambios sin guardar' : 'Guardado';
  }

  renderSelectors() {
    const chains = this.root.querySelector('[data-role=chain]'); const segments = this.root.querySelector('[data-role=segment]'); const selected = this.scene.presentation.selection;
    chains.replaceChildren(...this.scene.geometry.chains.map((c) => new Option(c.name, c.id, false, c.id === (selected.chainId || this.scene.geometry.chains[0]?.id))));
    const chain = activeChain(this.scene); const sm = new Map(this.scene.geometry.segments.map((s) => [s.id, s])); segments.replaceChildren(...chain.segmentIds.map((id) => new Option(sm.get(id)?.name || id, id, false, id === selected.segmentId)));
    const playhead = this.scene.presentation.playhead; const chainSegments = chain.segmentIds.map((id) => sm.get(id)).filter(Boolean); const total = chainSegments.reduce((sum, segment) => sum + segment.duration, 0); const activeIndex = Math.max(0, chainSegments.findIndex((segment) => segment.id === playhead.segmentId)); const t = chainSegments.slice(0, activeIndex).reduce((sum, segment) => sum + segment.duration, 0) + (chainSegments[activeIndex]?.duration || 1) * playhead.u; const value = playhead.scope === 'global' ? t : playhead.u; const max = playhead.scope === 'global' ? Math.max(1e-6, total) : 1; const range = this.root.querySelector('[data-role=u-range]'), number = this.root.querySelector('[data-role=u-number]'); range.max = max; number.max = max; range.value = value; number.value = Number(value.toFixed(5)); range.setAttribute('aria-label', playhead.scope === 'global' ? 'Parámetro global t' : 'Parámetro local u'); number.setAttribute('aria-label', playhead.scope === 'global' ? 'Valor de t' : 'Valor de u'); this.root.querySelector('[data-command=play]').textContent = this.playing ? '❚❚' : '▶';
  }

  renderPanel() {
    if (!this.scene) return; this.panelBody.replaceChildren();
    if (this.activeTab === 'controls') this.controlsPanel(); else if (this.activeTab === 'bases') this.basesPanel(); else if (this.activeTab === 'continuity') this.continuityPanel(); else this.measurementsPanel();
  }

  heading(title, subtitle) { const h = document.createElement('h2'); h.textContent = title; this.panelBody.append(h); if (subtitle) { const p = document.createElement('p'); p.className = 'muted'; p.textContent = subtitle; this.panelBody.append(p); } }
  section(title) { const h = document.createElement('h3'); h.textContent = title; this.panelBody.append(h); }
  controlGrid(items) { const grid = document.createElement('div'); grid.className = 'control-grid'; for (const item of items) { const label = document.createElement('label'); label.textContent = item.label; const input = item.element || document.createElement(item.type === 'select' ? 'select' : 'input'); const controlId = `control-${Math.random().toString(36).slice(2)}`; input.id = controlId; label.htmlFor = controlId; if (!item.element) { if (item.type === 'select') item.options.forEach(([value, text]) => input.add(new Option(text, value))); else input.type = item.type || 'number'; input.value = item.value; if (item.checked !== undefined) input.checked = item.checked; if (item.min !== undefined) input.min = item.min; if (item.max !== undefined) input.max = item.max; if (item.step !== undefined) input.step = item.step; input.addEventListener(item.event || 'change', () => item.on(input.type === 'checkbox' ? input.checked : input.value)); } grid.append(label, input); } this.panelBody.append(grid); return grid; }
  buttons(items) { const row = document.createElement('div'); row.className = 'button-row'; items.forEach(({ label, action, disabled, title }) => { const b = document.createElement('button'); b.textContent = label; b.disabled = !!disabled; if (title) b.title = title; b.addEventListener('click', action); row.append(b); }); this.panelBody.append(row); }

  controlsPanel() {
    const s = this.scene.presentation.settings; const segment = selectedSegment(this.scene); this.heading('Controles', segment ? `Editando ${segment.name}, grado ${segment.degree}` : 'Seleccioná un tramo o agregá puntos.');
    this.quickPane?.dispose(); const paneHost = document.createElement('div'); this.panelBody.append(paneHost); const quick = { grado: s.creationDegree, modo: s.creationMode, u: this.scene.presentation.playhead.u }; this.quickPane = new Pane({ container: paneHost, title: 'Ajustes rápidos' });
    this.quickPane.addBinding(quick, 'grado', { label: 'Grado', options: { Lineal: 1, Cuadrática: 2, Cúbica: 3 } }).on('change', (e) => this.setting('creationDegree', e.value));
    this.quickPane.addBinding(quick, 'modo', { label: 'Creación', options: { Independiente: 'independent', Encadenado: 'chained' } }).on('change', (e) => this.setting('creationMode', e.value));
    this.quickPane.addBinding(quick, 'u', { label: 'Parámetro u', min: 0, max: 1, step: .001 }).on('change', (e) => this.updatePlayhead('u', e.value));
    this.section('Creación'); this.controlGrid([
      { label: 'Grado activo', type: 'select', value: s.creationDegree, options: [[1, 'Lineal'], [2, 'Cuadrática'], [3, 'Cúbica']], on: (v) => this.setting('creationDegree', Number(v)) },
      { label: 'Modo', type: 'select', value: s.creationMode, options: [['independent', 'Independiente'], ['chained', 'Encadenado']], on: (v) => this.setting('creationMode', v) },
      { label: 'Ajustar a cuadrícula', type: 'checkbox', checked: s.snapToGrid, on: (v) => this.setting('snapToGrid', v) },
      { label: 'Paso de ajuste', value: s.snapStep, min: .000001, step: .05, on: (v) => this.setting('snapStep', Math.max(.000001, parseNumber(v))) },
    ]); this.buttons([{ label: 'Nueva cadena', action: () => this.newChain() }, { label: 'Descartar borrador', disabled: !this.scene.geometry.drafts.length, action: () => this.discardDraft() }]);
    if (segment) { this.section('Selección'); const pmap = pointMap(this.scene); this.controlGrid([{ label: 'Nombre', type: 'text', value: segment.name, on: (v) => this.store.transact('Renombrar tramo', (doc) => { doc.geometry.segments.find((x) => x.id === segment.id).name = v.slice(0, 120); }) }, { label: 'Duración h', value: segment.duration, min: 1e-6, max: 1e6, step: .1, on: (v) => this.store.transact('Cambiar duración', (doc) => { doc.geometry.segments.find((x) => x.id === segment.id).duration = Math.max(1e-6, Math.min(1e6, parseNumber(v))); applyConstraints(doc); }) }, { label: 'Eje de arrastre', type: 'select', value: s.dragAxis, options: [['free', 'Libre'], ['x', 'X'], ['y', 'Y']], on: (v) => this.setting('dragAxis', v) }]);
      this.buttons([{ label: 'Seleccionar puntos', action: () => this.store.transact('Seleccionar puntos', (doc) => { doc.presentation.selection.pointIds = [...segment.pointIds]; }) }, { label: 'Duplicar', action: () => this.duplicateSegment() }]);
      this.buttons([{ label: 'Dividir aquí', disabled: this.scene.presentation.playhead.u < 1e-4 || this.scene.presentation.playhead.u > .9999, action: () => this.store.transact('Dividir tramo', (doc) => splitSelected(doc)) }, { label: 'Elevar grado', disabled: segment.degree >= 3, action: () => this.store.transact('Elevar grado', (doc) => elevateSelected(doc)) }, { label: 'Congelar referencia', action: () => this.store.transact('Congelar referencia', (doc) => freezeSelected(doc)) }]);
      if (this.scene.presentation.selection.pointIds.length === 1) { const point = pmap.get(this.scene.presentation.selection.pointIds[0]); this.section('Punto seleccionado'); this.controlGrid([{ label: 'x', value: point.x, step: .1, on: (v) => this.editPoint(point.id, 'x', v) }, { label: 'y', value: point.y, step: .1, on: (v) => this.editPoint(point.id, 'y', v) }]); }
    }
    this.section('Capas'); this.controlGrid([
      ['Curvas', 'curveVisible'], ['Polígonos', 'controlsVisible'], ['Puntos', 'pointsVisible'], ['Rótulos', 'labelsVisible'], ['Cuadrícula', 'gridVisible'], ['De Casteljau', 'casteljauVisible'], ['Tangente unitaria T', 'vectorsVisible'], ["Primera derivada C'", 'firstDerivativeVisible'], ['Segunda derivada C\'\'', 'secondDerivativeVisible'], ['Normal principal', 'normalVisible'], ['Círculo osculador', 'osculatingCircleVisible'], ['Casco convexo', 'hullVisible'], ['Muestras', 'samplesVisible'], ['Referencias', 'referencesVisible'], ['Sondas', 'probesVisible']
    ].map(([label, key]) => ({ label, type: 'checkbox', checked: s[key], on: (v) => this.setting(key, v) })));
    this.section('Vectores'); this.controlGrid([{ label: "Escala C' / C''", value: s.vectorScale, min: 1, max: 120, step: 1, on: (v) => this.setting('vectorScale', Math.max(1, Math.min(120, parseNumber(v)))) }, { label: 'Longitud visual T', value: s.unitVectorLength, min: 10, max: 240, step: 5, on: (v) => this.setting('unitVectorLength', Math.max(10, Math.min(240, parseNumber(v)))) }, { label: "Color C'", type: 'color', value: s.tangentColor, on: (v) => this.setting('tangentColor', v) }, { label: 'Color T', type: 'color', value: s.unitTangentColor, on: (v) => this.setting('unitTangentColor', v) }]);
    this.section('Discretización'); this.controlGrid([{ label: 'Representación', type: 'select', value: s.samplingMode, options: [['smooth', 'Suave automático'], ['manual', 'Manual']], on: (v) => this.setting('samplingMode', v) }, { label: 'Color discretizada', type: 'color', value: s.samplingColor, on: (v) => this.setting('samplingColor', v) }, { label: 'Estrategia', type: 'select', value: s.samplingStrategy, options: [['parameter', 'Uniforme en u'], ['arcLength', 'Por distancia'], ['adaptive', 'Adaptativa visual']], on: (v) => this.setting('samplingStrategy', v) }, { label: 'Subdivisiones N', value: s.subdivisions, min: 1, max: 2048, step: 1, on: (v) => this.setting('subdivisions', Math.round(Math.max(1, Math.min(2048, parseNumber(v))))) }, { label: 'Tolerancia px', value: s.adaptiveTolerancePx, min: .1, max: 20, step: .1, on: (v) => this.setting('adaptiveTolerancePx', Math.max(.1, Math.min(20, parseNumber(v)))) }]);
    this.section('Estilo'); this.controlGrid([{ label: 'Color de curva', type: 'color', value: s.curveColor, on: (v) => this.setting('curveColor', v) }, { label: 'Grosor', value: s.curveWidth, min: .5, max: 12, step: .5, on: (v) => this.setting('curveWidth', Number(v)) }, { label: 'Radio de puntos', value: s.pointRadius, min: 2, max: 14, step: 1, on: (v) => this.setting('pointRadius', Number(v)) }, { label: 'Tamaño de rótulo', value: s.labelSize, min: 10, max: 40, step: 1, on: (v) => this.setting('labelSize', Number(v)) }]);
    this.section('Sesión y vistas'); this.controlGrid([{ label: 'Autoguardado local', type: 'checkbox', checked: s.autoSave, on: (v) => this.setting('autoSave', v) }]); this.buttons([{ label: 'Guardar vista', action: () => this.saveView() }, { label: 'Borrar datos locales', action: () => { localStorage.removeItem('bezier-lab-autosave-v1'); this.toast('Datos locales borrados'); } }]);
    if (this.scene.presentation.savedViews.length) { const viewSelect = document.createElement('select'); this.scene.presentation.savedViews.forEach((v) => viewSelect.add(new Option(v.name, v.id))); this.controlGrid([{ label: 'Vista guardada', element: viewSelect }]); this.buttons([{ label: 'Aplicar vista', action: () => this.applyView(viewSelect.value) }, { label: 'Eliminar vista', action: () => this.store.transact('Eliminar vista', (doc) => { doc.presentation.savedViews = doc.presentation.savedViews.filter((v) => v.id !== viewSelect.value); }) }]); }
  }

  basesPanel() {
    const segment = selectedSegment(this.scene); this.heading('Funciones base', 'Bernstein y la geometría comparten la misma fuente de verdad.'); if (!segment) return;
    const degree = segment.degree; const u = this.scene.presentation.playhead.u; const colors = ['#2563eb', '#d97706', '#059669', '#7c3aed']; const w = 300, h = 170, pad = 24; const svg = document.createElementNS(SVG_NS, 'svg'); svg.classList.add('chart'); svg.setAttribute('viewBox', `0 0 ${w} ${h}`); const axis = document.createElementNS(SVG_NS, 'path'); axis.setAttribute('d', `M${pad} ${h-pad}H${w-8}M${pad} ${h-pad}V8`); axis.setAttribute('stroke', '#94a3b8'); axis.setAttribute('fill', 'none'); svg.append(axis);
    for (let i = 0; i <= degree; i += 1) { const path = document.createElementNS(SVG_NS, 'path'); let d = ''; for (let k = 0; k <= 100; k += 1) { const t = k / 100, value = bernstein(degree, t)[i]; const x = pad + t * (w - pad - 8), y = h - pad - value * (h - pad - 12); d += `${k ? 'L' : 'M'}${x} ${y}`; } path.setAttribute('d', d); path.setAttribute('stroke', colors[i]); path.setAttribute('stroke-width', '2'); path.setAttribute('fill', 'none'); svg.append(path); }
    const cursor = document.createElementNS(SVG_NS, 'line'); cursor.setAttribute('x1', pad + u * (w - pad - 8)); cursor.setAttribute('x2', pad + u * (w - pad - 8)); cursor.setAttribute('y1', 8); cursor.setAttribute('y2', h - pad); cursor.setAttribute('stroke', '#172033'); cursor.setAttribute('stroke-dasharray', '3 3'); svg.append(cursor); this.panelBody.append(svg);
    const values = bernstein(degree, u); values.forEach((v, i) => { const row = document.createElement('div'); row.className = 'basis-value'; const name = document.createElement('span'); name.textContent = `B${i}^${degree}(u)`; name.style.color = colors[i]; const val = document.createElement('strong'); val.textContent = v.toFixed(6); row.append(name, val); this.panelBody.append(row); }); const sum = document.createElement('p'); sum.className = 'muted'; sum.textContent = `Σ Bi = ${values.reduce((a, b) => a + b, 0).toFixed(8)} · u = ${u.toFixed(4)}`; this.panelBody.append(sum);
  }

  continuityPanel() {
    const joins = joinsFor(this.scene); const s = this.scene.presentation.settings; this.heading('Continuidad', joins.length ? `${joins.length} uniones consecutivas` : 'La cadena necesita al menos dos tramos.'); this.controlGrid([{ label: 'Comparación', type: 'select', value: s.continuityMode, options: [['global', 'Global t'], ['local', 'Local u']], on: (v) => this.setting('continuityMode', v) }, { label: 'Tol. relativa', value: s.relTol, step: 1e-8, on: (v) => this.setting('relTol', Math.max(0, parseNumber(v))) }, { label: 'Tol. angular (°)', value: s.angleDeg, step: .01, on: (v) => this.setting('angleDeg', Math.max(0, parseNumber(v))) }]); if (!joins.length) return;
    const table = document.createElement('table'); table.className = 'continuity-table'; const head = table.createTHead().insertRow(); ['Unión', 'C0', 'G1', 'C1', 'C2'].forEach((x) => { const th = document.createElement('th'); th.textContent = x; head.append(th); }); const body = table.createTBody(); joins.forEach((join, i) => { const row = body.insertRow(); const name = row.insertCell(); name.textContent = `${join.left.name} → ${join.right.name}`; for (const key of ['c0', 'g1', 'c1', 'c2']) { const cell = row.insertCell(); const value = join.result[key]; cell.textContent = value === null ? '—' : value ? '✓' : '×'; cell.className = value === null ? 'undefined' : value ? 'pass' : 'fail'; cell.title = value === null ? 'No definido' : value ? 'Cumple dentro de tolerancia' : 'No cumple'; } row.addEventListener('click', () => { this.selectedJoin = i; this.renderPanel(); }); }); this.panelBody.append(table);
    const join = joins[this.selectedJoin || 0]; const r = join.result; this.section('Detalle de la unión'); const detail = document.createElement('p'); detail.className = 'muted'; detail.textContent = `Separación ${r.separation.toExponential(3)} · ángulo ${r.angle === null ? 'no definido' : (r.angle * 180 / Math.PI).toFixed(4) + '°'} · hA=${join.left.duration} · hB=${join.right.duration}`; this.panelBody.append(detail);
    this.buttons([{ label: 'Ajustar C0', action: () => this.adjustJoin(join, 'C0') }, { label: 'Ajustar G1', disabled: Math.hypot(r.vA.x, r.vA.y) < s.relTol, action: () => this.adjustJoin(join, 'G1') }, { label: 'Ajustar C1', action: () => this.adjustJoin(join, 'C1') }, { label: 'Ajustar C2', disabled: join.right.degree < 2, action: () => this.adjustJoin(join, 'C2') }]);
    const existing = this.scene.geometry.constraints.find((c) => c.leftSegmentId === join.left.id && c.rightSegmentId === join.right.id); this.section('Bloqueo dirigido A → B');
    if (join.left.degree !== 3 || join.right.degree !== 3) { const note = document.createElement('div'); note.className = 'notice'; note.textContent = 'Los bloqueos persistentes requieren dos tramos cúbicos.'; this.panelBody.append(note); }
    else { const lockType = document.createElement('select'); ['C0', 'G1', 'C1', 'C2'].forEach((type) => lockType.add(new Option(type, type, false, type === (existing?.type || 'C1')))); this.controlGrid([{ label: 'Restricción', element: lockType }]); this.buttons([{ label: existing?.enabled ? 'Liberar controles' : 'Activar bloqueo', action: () => this.toggleConstraint(join, lockType.value) }]); if (existing?.suspended) { const note = document.createElement('div'); note.className = 'notice'; note.textContent = 'G1 suspendida: la tangente izquierda es nula.'; this.panelBody.append(note); } }
  }

  measurementsPanel() {
    const segment = selectedSegment(this.scene); this.heading('Mediciones', 'Valores analíticos; no dependen de la discretización visible.'); if (!segment) return; const points = pointsFor(this.scene, segment), u = this.scene.presentation.playhead.u, f = curvatureFrame(points, u, this.scene.presentation.settings); const lengthData = arcLengthTable(points, 1e-5).length; const dl = document.createElement('dl'); dl.className = 'measure-grid'; const entries = [['u', u.toFixed(6)], ['C(u)', `(${f.position.x.toFixed(6)}, ${f.position.y.toFixed(6)})`], ["C'(u)", `(${f.first.x.toFixed(6)}, ${f.first.y.toFixed(6)})`], ["C''(u)", `(${f.second.x.toFixed(6)}, ${f.second.y.toFixed(6)})`], ['Velocidad', f.speed.toFixed(6)], ['Curvatura κs', f.defined ? f.signedCurvature.toFixed(8) : 'No definida'], ['Radio ρ', f.normalDefined ? f.radius.toFixed(6) : f.defined ? '∞' : 'No definido'], ['Longitud aprox.', lengthData.toFixed(7)]]; entries.forEach(([a, b]) => { const dt = document.createElement('dt'); dt.textContent = a; const dd = document.createElement('dd'); dd.textContent = b; dl.append(dt, dd); }); this.panelBody.append(dl);
    this.buttons([{ label: 'Fijar evaluación', disabled: this.scene.presentation.probes.length >= 12, action: () => this.addProbe() }, { label: 'Borrar sondas', disabled: !this.scene.presentation.probes.length, action: () => this.store.transact('Borrar sondas', (doc) => { doc.presentation.probes = []; }) }]);
  }

  renderMath() {
    const host = this.root.querySelector('.math-content'); if (!host || !this.scene) return; host.replaceChildren(); const segment = selectedSegment(this.scene); if (!segment) { host.textContent = 'Seleccioná un tramo para ver sus formulaciones.'; return; } const n = segment.degree, u = this.scene.presentation.playhead.u, points = pointsFor(this.scene, segment), coeff = powerCoefficients(points); const title = document.createElement('p'); title.textContent = `${segment.name} · grado ${n} · u=${u.toFixed(4)} · h=${segment.duration}`; host.append(title); const formulas = [`C(u)=\\sum_{i=0}^{${n}} B_i^{${n}}(u)P_i`, `B_i^n(u)={n\\choose i}(1-u)^{n-i}u^i`, `C(u)=${bernstein(n, u).map((b, i) => `${b.toFixed(4)}P_${i}`).join('+')}`, `P_i^r=(1-u)P_i^{r-1}+uP_{i+1}^{r-1}`, `C'(u)=n\\sum B_i^{n-1}(u)(P_{i+1}-P_i)`, `C''(u)=n(n-1)\\sum B_i^{n-2}(u)(P_{i+2}-2P_{i+1}+P_i)`]; formulas.forEach((formula) => { const div = document.createElement('div'); div.className = 'formula'; katex.render(formula, div, { throwOnError: false, displayMode: true }); host.append(div); }); const p = document.createElement('p'); p.textContent = `Coeficientes de mayor a menor grado: ${coeff.map((c) => `(${c.x.toFixed(3)}, ${c.y.toFixed(3)})`).join(' · ')}`; host.append(p); const props = document.createElement('p'); props.className = 'muted'; props.textContent = 'Interpolación de extremos · combinación convexa · casco convexo · invariancia afín. La suavidad interior no garantiza continuidad entre tramos.'; host.append(props);
  }

  setTool(tool) { this.tool = tool; this.render(this.store.status()); this.svg.focus(); }
  setting(key, value) { this.store.transact(`Cambiar ${key}`, (doc) => { doc.presentation.settings[key] = value; }); }
  updatePlayhead(key, value, transactional = false) { const apply = (doc) => { doc.presentation.playhead[key] = value; }; if (transactional) this.store.transact('Cambiar recorrido', apply); else { apply(this.scene); this.store.notify('playhead'); } }
  setTimelineValue(value) { if (!Number.isFinite(value)) return; const playhead = this.scene.presentation.playhead; if (playhead.scope === 'local') { playhead.u = Math.max(0, Math.min(1, value)); this.store.notify('playhead'); return; } const chain = this.scene.geometry.chains.find((c) => c.id === playhead.chainId) || activeChain(this.scene), sm = new Map(this.scene.geometry.segments.map((s) => [s.id, s])), segments = chain.segmentIds.map((id) => sm.get(id)).filter(Boolean), total = segments.reduce((sum, segment) => sum + segment.duration, 0); let t = Math.max(0, Math.min(total, value)), accumulated = 0, active = segments.at(-1), u = 1; for (const segment of segments) { if (t < accumulated + segment.duration || (t === accumulated && accumulated === 0)) { active = segment; u = (t - accumulated) / segment.duration; break; } accumulated += segment.duration; } if (active) { playhead.segmentId = active.id; playhead.chainId = chain.id; playhead.u = Math.max(0, Math.min(1, u)); this.scene.presentation.selection.segmentId = active.id; this.scene.presentation.selection.chainId = chain.id; } this.store.notify('playhead'); }
  editPoint(id, axis, value) { const n = parseNumber(value); if (!Number.isFinite(n)) return this.toast('Valor numérico inválido'); if (dependentPointIds(this.scene).has(id)) return this.toast('Este control se mantiene por restricción'); this.store.transact('Editar coordenada', (doc) => { const p = doc.geometry.points.find((x) => x.id === id); p[axis] = n; applyConstraints(doc); }); }
  selectSegment(id) { this.scene.presentation.selection.segmentId = id; this.scene.presentation.selection.pointIds = []; this.scene.presentation.playhead.segmentId = id; const chain = this.scene.geometry.chains.find((c) => c.segmentIds.includes(id)); this.scene.presentation.selection.chainId = chain?.id || null; this.scene.presentation.playhead.chainId = chain?.id || null; this.store.notify('selection'); }

  command(command) {
    const actions = {
      new: () => this.confirmReplace(() => this.store.replace(createScene('Nueva escena'))),
      open: () => this.fileInput.click(), save: () => this.downloadJson(), undo: () => this.store.undo(), redo: () => this.store.redo(), fit: () => this.fit(),
      illustration: () => this.toggleIllustration(), export: () => this.exportDialog(), palette: () => this.commandPalette(), panel: () => { this.panelOpen = !this.panelOpen; this.panel.classList.toggle('open', this.panelOpen); },
      play: () => { this.playing = !this.playing; this.lastFrame = performance.now(); this.render(this.store.status()); }, restart: () => { this.playing = false; this.updatePlayhead('u', 0); }, probe: () => this.addProbe(),
    }; actions[command]?.();
  }

  keydown(e) {
    const mod = e.ctrlKey || e.metaKey;
    if (mod && e.key.toLowerCase() === 'k') { e.preventDefault(); return this.commandPalette(); }
    if (mod && e.key.toLowerCase() === 's') { e.preventDefault(); return this.downloadJson(); }
    if (mod && e.key.toLowerCase() === 'o') { e.preventDefault(); return this.fileInput.click(); }
    if (mod && e.key.toLowerCase() === 'z') { e.preventDefault(); return e.shiftKey ? this.store.redo() : this.store.undo(); }
    if (mod && e.key.toLowerCase() === 'y') { e.preventDefault(); return this.store.redo(); }
    if (isEditing()) return;
    const key = e.key.toLowerCase(); const tool = Object.entries(TOOLS).find(([, [shortcut]]) => shortcut.toLowerCase() === key)?.[0]; if (tool) this.setTool(tool);
    if (key === 'f') this.fit(e.shiftKey); if (key === 'i' && selectedSegment(this.scene)) { this.scene.presentation.isolationSegmentId = this.scene.presentation.isolationSegmentId ? null : selectedSegment(this.scene).id; this.store.notify('isolation'); }
    if (e.key === 'Delete') this.store.transact('Borrar selección', (doc) => deleteSelection(doc));
    if (e.key === 'Tab' && document.activeElement === this.svg) { e.preventDefault(); this.toggleIllustration(); }
    if (e.key === 'Escape') { if (this.lab.classList.contains('illustration')) this.toggleIllustration(false); else if (this.pointer?.original) { this.scene.geometry.points = this.pointer.original; this.pointer = null; this.store.notify('cancel-drag'); } else this.setTool('select'); }
  }

  eventPoint(e) { const r = this.svg.getBoundingClientRect(); return { x: e.clientX - r.left, y: e.clientY - r.top }; }
  snap(p) { const s = this.scene.presentation.settings; if (!s.snapToGrid) return p; return { x: Math.round(p.x / s.snapStep) * s.snapStep, y: Math.round(p.y / s.snapStep) * s.snapStep }; }
  pointPointer(e, id) {
    e.stopPropagation();
    if (this.tool === 'delete') { this.scene.presentation.selection.pointIds = [id]; this.store.transact('Borrar punto', (doc) => deleteSelection(doc)); return; }
    if (this.tool !== 'select') return;
    if (dependentPointIds(this.scene).has(id)) { this.toast('Este control se mantiene por restricción'); return; }
    const selected = this.scene.presentation.selection.pointIds; if (e.shiftKey) this.scene.presentation.selection.pointIds = selected.includes(id) ? selected.filter((x) => x !== id) : [...selected, id]; else if (!selected.includes(id)) this.scene.presentation.selection.pointIds = [id];
    const pmap = pointMap(this.scene); const ids = this.scene.presentation.selection.pointIds; const start = this.eventPoint(e); const origin = new Map(ids.map((pid) => [pid, { ...pmap.get(pid) }])); this.pointer = { type: 'points', start, ids, origin, original: structuredClone(this.scene.geometry.points), moved: false }; this.svg.setPointerCapture(e.pointerId); this.playing = false; this.store.notify('selection');
  }
  segmentPointer(e, id) { e.stopPropagation(); if (this.tool === 'delete') { this.selectSegment(id); this.store.transact('Eliminar tramo', (doc) => deleteSelection(doc)); return; } if (this.tool === 'select' || this.tool === 'explore') { this.selectSegment(id); if (this.tool === 'explore') this.exploreAt(e); } }
  backgroundPointer(e) {
    if (e.target !== this.svg && !e.target.classList.contains('grid-layer') && !e.target.classList.contains('grid-line')) return; const pos = this.eventPoint(e); const rect = this.svg.getBoundingClientRect();
    if (this.tool === 'add') { let world = this.snap(screenToWorld(this.scene.presentation.camera, rect.width, rect.height, pos)); this.store.transact('Agregar punto', (doc) => addDraftPoint(doc, world)); return; }
    if (this.tool === 'pan' || e.buttons === 4 || this.spaceDown) { this.pointer = { type: 'pan', start: pos, camera: { ...this.scene.presentation.camera } }; this.svg.setPointerCapture(e.pointerId); return; }
    if (this.tool === 'select') { if (!e.shiftKey) this.scene.presentation.selection.pointIds = []; this.pointer = { type: 'box', start: pos, additive: e.shiftKey }; const box = document.createElementNS(SVG_NS, 'rect'); box.classList.add('selection-rect'); box.dataset.selectionRect = 'true'; this.svg.append(box); this.store.notify('selection'); }
    if (this.tool === 'explore') this.exploreAt(e);
  }
  pointerMove(e) {
    const pos = this.eventPoint(e); const rect = this.svg.getBoundingClientRect(); const world = screenToWorld(this.scene.presentation.camera, rect.width, rect.height, pos); this.root.querySelector('[data-status=coords]').textContent = `x ${world.x.toFixed(3)} · y ${world.y.toFixed(3)}`;
    if (!this.pointer) return;
    if (this.pointer.type === 'pan') { const dx = pos.x - this.pointer.start.x, dy = pos.y - this.pointer.start.y, c = this.scene.presentation.camera; c.centerX = this.pointer.camera.centerX - dx / c.pixelsPerUnit; c.centerY = this.pointer.camera.centerY + dy / c.pixelsPerUnit; this.store.notify('pan'); }
    if (this.pointer.type === 'points') { const pmap = pointMap(this.scene); const startWorld = screenToWorld(this.scene.presentation.camera, rect.width, rect.height, this.pointer.start); const delta = { x: world.x - startWorld.x, y: world.y - startWorld.y }; const axis = this.scene.presentation.settings.dragAxis; this.pointer.ids.forEach((id) => { const original = this.pointer.origin.get(id); const proposal = this.snap({ x: original.x + (axis === 'y' ? 0 : delta.x), y: original.y + (axis === 'x' ? 0 : delta.y) }); Object.assign(pmap.get(id), proposal); }); applyConstraints(this.scene); this.pointer.moved = true; this.store.notify('drag'); }
    if (this.pointer.type === 'box') { const x = Math.min(pos.x, this.pointer.start.x), y = Math.min(pos.y, this.pointer.start.y), w = Math.abs(pos.x - this.pointer.start.x), h = Math.abs(pos.y - this.pointer.start.y); const box = this.svg.querySelector('[data-selection-rect]'); if (box) Object.entries({ x, y, width: w, height: h }).forEach(([k, v]) => box.setAttribute(k, v)); }
  }
  pointerUp(e) {
    if (!this.pointer) return; const current = this.pointer; this.pointer = null;
    if (current.type === 'points' && current.moved) { const final = structuredClone(this.scene.geometry.points); this.scene.geometry.points = current.original; this.store.transact('Mover puntos', (doc) => { doc.geometry.points = final; }); }
    if (current.type === 'box') { const pos = this.eventPoint(e), minX = Math.min(pos.x, current.start.x), maxX = Math.max(pos.x, current.start.x), minY = Math.min(pos.y, current.start.y), maxY = Math.max(pos.y, current.start.y), rect = this.svg.getBoundingClientRect(), camera = this.scene.presentation.camera; const found = this.scene.geometry.points.filter((p) => { const q = worldToScreen(camera, rect.width, rect.height, p); return q.x >= minX && q.x <= maxX && q.y >= minY && q.y <= maxY; }).map((p) => p.id); this.scene.presentation.selection.pointIds = current.additive ? [...new Set([...this.scene.presentation.selection.pointIds, ...found])] : found; this.store.notify('box selection'); }
    this.svg.releasePointerCapture?.(e.pointerId);
  }
  exploreAt(e) { const segment = selectedSegment(this.scene); if (!segment) return; const rect = this.svg.getBoundingClientRect(), target = this.eventPoint(e), points = pointsFor(this.scene, segment); let best = { u: 0, d: Infinity }; for (let i = 0; i <= 300; i += 1) { const u = i / 300, p = worldToScreen(this.scene.presentation.camera, rect.width, rect.height, evaluate(points, u)), d = Math.hypot(p.x - target.x, p.y - target.y); if (d < best.d) best = { u, d }; } let lo = Math.max(0, best.u - 1 / 300), hi = Math.min(1, best.u + 1 / 300); for (let i = 0; i < 18; i += 1) { const a = lo + (hi - lo) / 3, b = hi - (hi - lo) / 3; const da = (() => { const p = worldToScreen(this.scene.presentation.camera, rect.width, rect.height, evaluate(points, a)); return Math.hypot(p.x - target.x, p.y - target.y); })(); const db = (() => { const p = worldToScreen(this.scene.presentation.camera, rect.width, rect.height, evaluate(points, b)); return Math.hypot(p.x - target.x, p.y - target.y); })(); if (da < db) hi = b; else lo = a; } if (best.d <= 16) this.updatePlayhead('u', (lo + hi) / 2); }
  wheel(e) { e.preventDefault(); const factor = Math.exp(-e.deltaY * .0015); this.zoom(factor, this.eventPoint(e)); }
  zoom(factor, anchor) { const camera = this.scene.presentation.camera, rect = this.svg.getBoundingClientRect(), screen = anchor || { x: rect.width / 2, y: rect.height / 2 }, before = screenToWorld(camera, rect.width, rect.height, screen); camera.pixelsPerUnit = Math.max(1e-7, Math.min(1e7, camera.pixelsPerUnit * factor)); const after = screenToWorld(camera, rect.width, rect.height, screen); camera.centerX += before.x - after.x; camera.centerY += before.y - after.y; this.store.notify('zoom'); }
  fit(selectionOnly = false) { const scene = this.scene, saved = scene.presentation.selection.pointIds; if (!selectionOnly) scene.presentation.selection.pointIds = []; const b = fitBounds(scene); scene.presentation.selection.pointIds = saved; if (!b) return; const r = this.svg.getBoundingClientRect(), dx = Math.max(2, b.maxX - b.minX), dy = Math.max(2, b.maxY - b.minY), margin = 64; scene.presentation.camera.centerX = (b.minX + b.maxX) / 2; scene.presentation.camera.centerY = (b.minY + b.maxY) / 2; scene.presentation.camera.pixelsPerUnit = Math.max(1e-7, Math.min(1e7, Math.min((r.width - margin * 2) / dx, (r.height - margin * 2) / dy))); this.store.notify('fit'); }

  newChain() { this.store.transact('Nueva cadena', (doc) => { const chain = { id: makeId('chain'), name: `Cadena ${doc.geometry.chains.length + 1}`, segmentIds: [] }; doc.geometry.chains.push(chain); doc.presentation.selection = { segmentId: null, pointIds: [], chainId: chain.id }; }); }
  discardDraft() { this.store.transact('Descartar borrador', (doc) => { const chain = activeChain(doc); const drafts = doc.geometry.drafts.filter((d) => d.chainId === chain.id); if (!drafts.length) return; const draft = drafts.at(-1); doc.geometry.drafts = doc.geometry.drafts.filter((d) => d.id !== draft.id); const used = new Set([...doc.geometry.segments.flatMap((s) => s.pointIds), ...doc.geometry.drafts.flatMap((d) => d.pointIds)]); doc.geometry.points = doc.geometry.points.filter((p) => used.has(p.id)); }); }
  duplicateSegment() { this.store.transact('Duplicar tramo', (doc) => { const segment = selectedSegment(doc); if (!segment) return; const shift = 24 / doc.presentation.camera.pixelsPerUnit; const ids = pointsFor(doc, segment).map((p) => { const q = { id: makeId('point'), x: p.x + shift, y: p.y - shift }; doc.geometry.points.push(q); return q.id; }); const copy = { ...structuredClone(segment), id: makeId('segment'), name: `${segment.name} copia`, pointIds: ids }; doc.geometry.segments.push(copy); const chain = doc.geometry.chains.find((c) => c.segmentIds.includes(segment.id)); chain.segmentIds.splice(chain.segmentIds.indexOf(segment.id) + 1, 0, copy.id); doc.presentation.selection.segmentId = copy.id; }); }
  addProbe() { const segment = selectedSegment(this.scene); if (!segment) return this.toast('Seleccioná un tramo'); if (this.scene.presentation.probes.length >= 12) return this.toast('Máximo de 12 sondas'); this.store.transact('Fijar evaluación', (doc) => { doc.presentation.probes.push({ id: makeId('probe'), segmentId: segment.id, u: doc.presentation.playhead.u, label: `u=${doc.presentation.playhead.u.toFixed(3)}`, visible: true, showVectors: false, showCasteljau: false }); }); }
  adjustJoin(join, type) { this.store.transact(`Ajustar ${type}`, (doc) => { const left = doc.geometry.segments.find((x) => x.id === join.left.id), right = doc.geometry.segments.find((x) => x.id === join.right.id), pmap = pointMap(doc), A = pointsFor(doc, left), B = pointsFor(doc, right); const end = A.at(-1); Object.assign(B[0], end); if (type === 'C0') return; const tangent = { x: A.at(-1).x - A.at(-2).x, y: A.at(-1).y - A.at(-2).y }, len = Math.hypot(tangent.x, tangent.y); if (!len) return; if (type === 'G1') { const current = Math.hypot(B[1].x - B[0].x, B[1].y - B[0].y) || len; B[1].x = B[0].x + tangent.x / len * current; B[1].y = B[0].y + tangent.y / len * current; return; } const n = left.degree, m = right.degree, ratio = (right.duration / m) * (n / left.duration); B[1].x = B[0].x + tangent.x * ratio; B[1].y = B[0].y + tangent.y * ratio; if (type === 'C2' && m >= 2) { const second = n >= 2 ? { x: n * (n - 1) * (A.at(-1).x - 2 * A.at(-2).x + A.at(-3).x) / left.duration ** 2, y: n * (n - 1) * (A.at(-1).y - 2 * A.at(-2).y + A.at(-3).y) / left.duration ** 2 } : { x: 0, y: 0 }; const f = right.duration ** 2 / (m * (m - 1)); B[2].x = 2 * B[1].x - B[0].x + f * second.x; B[2].y = 2 * B[1].y - B[0].y + f * second.y; } }); }
  toggleConstraint(join, type) { this.store.transact('Cambiar restricción', (doc) => { const index = doc.geometry.constraints.findIndex((c) => c.leftSegmentId === join.left.id && c.rightSegmentId === join.right.id); if (index >= 0 && doc.geometry.constraints[index].enabled) { doc.geometry.constraints[index].enabled = false; return; } const right = doc.geometry.segments.find((s) => s.id === join.right.id); const B = pointsFor(doc, right); const constraint = { id: index >= 0 ? doc.geometry.constraints[index].id : makeId('constraint'), leftSegmentId: join.left.id, rightSegmentId: join.right.id, type, enabled: true, g1HandleLength: type === 'G1' ? Math.max(1e-12, Math.hypot(B[1].x - B[0].x, B[1].y - B[0].y)) : null }; if (index >= 0) doc.geometry.constraints[index] = constraint; else doc.geometry.constraints.push(constraint); applyConstraints(doc); }); }

  tick(time) { if (this.playing && !document.hidden) { const delta = Math.min(.1, (time - this.lastFrame) / 1000), playhead = this.scene.presentation.playhead; if (playhead.scope === 'global') { const chain = this.scene.geometry.chains.find((c) => c.id === playhead.chainId) || activeChain(this.scene), sm = new Map(this.scene.geometry.segments.map((s) => [s.id, s])), segments = chain.segmentIds.map((id) => sm.get(id)).filter(Boolean), total = segments.reduce((sum, segment) => sum + segment.duration, 0), index = Math.max(0, segments.findIndex((s) => s.id === playhead.segmentId)), current = segments.slice(0, index).reduce((sum, segment) => sum + segment.duration, 0) + (segments[index]?.duration || 1) * playhead.u; let next = current + delta * (playhead.speed || 1) * total / 8; if (next >= total) { if (playhead.loop) next %= total; else { next = total; this.playing = false; } } this.setTimelineValue(next); } else { let u = playhead.u + delta * (playhead.speed || 1) / 8; if (u >= 1) { if (playhead.loop) u %= 1; else { u = 1; this.playing = false; } } playhead.u = u; this.store.notify('animation'); } } this.lastFrame = time; requestAnimationFrame((t) => this.tick(t)); }
  toggleMath(force) { const panel = this.root.querySelector('.math-panel'); panel.classList.toggle('open', force ?? !panel.classList.contains('open')); }
  toggleIllustration(force) { this.lab.classList.toggle('illustration', force ?? !this.lab.classList.contains('illustration')); if (this.lab.classList.contains('illustration')) this.toast('Modo ilustración · Tab o Esc para salir'); }
  openExample(id) { const entry = this.examples.find((x) => x.id === id); if (entry) this.confirmReplace(() => { this.store.replace(hydrateScene(entry.scene), `Ejemplo ${entry.title}`); requestAnimationFrame(() => this.fit()); this.showExampleInfo(entry); }); }
  showExampleInfo(entry) {
    const metadata = entry.scene?.metadata || {}; const description = entry.description || metadata.description; const howTo = entry.howTo || metadata.howTo; const expected = expectedText(entry.expected ?? metadata.expected);
    if (!description && !howTo && !expected) return;
    const modal = this.modal(`Ejemplo ${entry.id.split(':').at(-1).slice(0, 2)} · ${entry.title}`); modal.root.querySelector('.modal').classList.add('example-dialog'); modal.cancel.remove();
    const intro = document.createElement('p'); intro.className = 'example-intro'; intro.textContent = description || 'Escena docente del catálogo.'; modal.body.append(intro);
    const addSection = (title, text) => { if (!text) return; const heading = document.createElement('h3'); heading.textContent = title; const paragraph = document.createElement('p'); paragraph.textContent = text; modal.body.append(heading, paragraph); };
    addSection('Qué probar', howTo); addSection('Resultado esperado', expected);
    modal.confirm.textContent = 'Cerrar explicación'; modal.confirm.addEventListener('click', modal.close); modal.confirm.focus();
  }
  confirmReplace(action) { if (!this.store.status().dirty || confirm('Hay cambios sin guardar. ¿Descartarlos?')) action(); }
  restoreSession() { try { const raw = localStorage.getItem('bezier-lab-autosave-v1'); return raw ? validateScene(JSON.parse(raw)) : null; } catch { return null; } }
  scheduleAutosave() { clearTimeout(this.autosaveTimer); if (!this.scene?.presentation.settings.autoSave) return; this.autosaveTimer = setTimeout(() => { try { localStorage.setItem('bezier-lab-autosave-v1', JSON.stringify(this.scene)); this.root.querySelector('[data-status=autosave]').textContent = 'Autosave actualizado'; } catch { this.toast('No se pudo guardar la sesión local'); } }, 750); }
  async importFile(file) { if (!file) return; this.fileInput.value = ''; if (file.size > 10 * 1024 * 1024) return this.toast('El archivo supera 10 MiB'); try { const data = JSON.parse(await file.text()); if (data.format === 'bezier-lab-catalog' && data.version === 1 && Array.isArray(data.examples)) { const prefix = safeName(data.title || file.name); const imported = data.examples.map((entry) => ({ ...entry, id: `${prefix}:${entry.id}`, scene: validateScene(entry.scene) })); this.examples.push(...imported); const select = this.root.querySelector('[data-role=examples]'); imported.forEach((ex) => select.insertBefore(new Option(`+ ${ex.title}`, ex.id), select.lastElementChild)); this.toast(`${imported.length} ejemplos agregados`); return; } const valid = validateScene(data); this.confirmReplace(() => { this.store.replace(valid, 'Abrir escena'); requestAnimationFrame(() => this.fit()); }); } catch (error) { this.toast(`Archivo rechazado: ${error.message}`); } }
  download(content, type, filename) { const blob = new Blob([content], { type }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = filename; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  downloadJson() { this.download(JSON.stringify(this.scene, null, 2), 'application/json;charset=utf-8', `${safeName(this.scene.title)}.json`); this.store.markSaved(); }
  downloadCatalog() { const catalog = { format: 'bezier-lab-catalog', version: 1, title: 'Casos docentes de curvas Bézier', examples: this.examples.filter((e) => !e.id.includes(':')).map(({ id, title, description, howTo, scene }) => ({ id, title, description, howTo, tags: scene.metadata.tags || [], scene, expected: scene.metadata.expected || {} })) }; this.download(JSON.stringify(catalog, null, 2), 'application/json;charset=utf-8', 'catalogo-bezier.json'); }
  saveView() { const name = prompt('Nombre de la vista', `Vista ${this.scene.presentation.savedViews.length + 1}`); if (!name) return; this.store.transact('Guardar vista', (doc) => { doc.presentation.savedViews.push({ id: makeId('view'), name: name.slice(0, 120), camera: structuredClone(doc.presentation.camera), settings: structuredClone(doc.presentation.settings), selection: structuredClone(doc.presentation.selection), playhead: structuredClone(doc.presentation.playhead), isolationSegmentId: doc.presentation.isolationSegmentId }); }); }
  applyView(id) { this.store.transact('Aplicar vista', (doc) => { const view = doc.presentation.savedViews.find((v) => v.id === id); if (!view) return; doc.presentation.camera = structuredClone(view.camera); doc.presentation.settings = { ...doc.presentation.settings, ...structuredClone(view.settings) }; doc.presentation.selection = structuredClone(view.selection); doc.presentation.playhead = structuredClone(view.playhead); doc.presentation.isolationSegmentId = view.isolationSegmentId || null; }); }
  exportDialog() { const modal = this.modal('Exportar ilustración'); modal.body.innerHTML = `<label>Formato</label><select data-field="format"><option value="svg">SVG autónomo</option><option value="png">PNG</option></select><label>Resolución</label><select data-field="size"><option value="1920x1080">1920 × 1080</option><option value="3840x2160">3840 × 2160</option><option value="1200x1200">1200 × 1200</option></select><label><input data-field="transparent" type="checkbox" style="width:auto;height:auto"> Fondo transparente</label>`; modal.confirm.textContent = 'Exportar'; modal.confirm.addEventListener('click', async () => { const format = modal.body.querySelector('[data-field=format]').value, [width, height] = modal.body.querySelector('[data-field=size]').value.split('x').map(Number), transparent = modal.body.querySelector('[data-field=transparent]').checked; const svg = this.renderer.serialize(structuredClone(this.scene), { width, height, transparent }); const date = new Date().toISOString().slice(0, 10), name = `${safeName(this.scene.title)}-escena-${date}`; if (format === 'svg') this.download(svg, 'image/svg+xml;charset=utf-8', `${name}.svg`); else await this.exportPng(svg, width, height, name); modal.close(); }); }
  async exportPng(svg, width, height, name) { if (width > 8192 || height > 8192 || width * height > 32e6) return this.toast('La imagen excede el límite de 32 megapíxeles'); const img = new Image(); const url = URL.createObjectURL(new Blob([svg], { type: 'image/svg+xml' })); await new Promise((resolve, reject) => { img.onload = resolve; img.onerror = reject; img.src = url; }); try { const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; canvas.getContext('2d').drawImage(img, 0, 0); const blob = await new Promise((resolve) => canvas.toBlob(resolve, 'image/png')); const out = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = out; a.download = `${name}.png`; a.click(); setTimeout(() => URL.revokeObjectURL(out), 1000); } finally { URL.revokeObjectURL(url); } }
  modal(title) { const back = document.createElement('div'); back.className = 'modal-backdrop'; const box = document.createElement('section'); box.className = 'modal'; box.setAttribute('role', 'dialog'); box.setAttribute('aria-modal', 'true'); const h = document.createElement('h2'); h.textContent = title; const body = document.createElement('div'); const actions = document.createElement('div'); actions.className = 'actions'; const cancel = document.createElement('button'); cancel.textContent = 'Cancelar'; const confirmButton = document.createElement('button'); confirmButton.className = 'primary'; const close = () => back.remove(); cancel.addEventListener('click', close); back.addEventListener('click', (event) => { if (event.target === back) close(); }); back.addEventListener('keydown', (event) => { if (event.key === 'Escape') { event.stopPropagation(); close(); } }); actions.append(cancel, confirmButton); box.append(h, body, actions); back.append(box); this.root.append(back); cancel.focus(); return { root: back, body, confirm: confirmButton, cancel, close }; }
  commandPalette() { const modal = this.modal('Paleta de comandos'); modal.root.querySelector('.actions').remove(); modal.root.querySelector('.modal').classList.add('palette'); const input = document.createElement('input'); input.placeholder = 'Buscar comando…'; input.setAttribute('aria-label', 'Buscar comando'); const list = document.createElement('div'); list.className = 'command-list'; modal.body.append(input, list); const commands = [{ n: 'Seleccionar', k: 'V', a: () => this.setTool('select') }, { n: 'Agregar puntos', k: 'A', a: () => this.setTool('add') }, { n: 'Borrar', k: 'D', a: () => this.setTool('delete') }, { n: 'Explorar curva', k: 'E', a: () => this.setTool('explore') }, { n: 'Desplazar vista', k: 'H', a: () => this.setTool('pan') }, { n: 'Nueva cadena', a: () => this.newChain() }, { n: 'Encuadrar todo', k: 'F', a: () => this.fit() }, { n: 'Dividir aquí', a: () => this.store.transact('Dividir tramo', (d) => splitSelected(d)) }, { n: 'Elevar grado', a: () => this.store.transact('Elevar grado', (d) => elevateSelected(d)) }, { n: 'Congelar referencia', a: () => this.store.transact('Congelar referencia', (d) => freezeSelected(d)) }, { n: 'Fijar sonda', a: () => this.addProbe() }, { n: 'Guardar escena', k: 'Ctrl+S', a: () => this.downloadJson() }, { n: 'Cargar escena o catálogo', k: 'Ctrl+O', a: () => this.fileInput.click() }, { n: 'Descargar catálogo', a: () => this.downloadCatalog() }, { n: 'Guardar vista', a: () => this.saveView() }, { n: 'Modo ilustración', k: 'Tab', a: () => this.toggleIllustration() }, { n: 'Exportar', a: () => this.exportDialog() }]; const draw = () => { list.replaceChildren(); commands.filter((c) => c.n.toLowerCase().includes(input.value.toLowerCase())).forEach((c) => { const b = document.createElement('button'); b.className = 'command-item'; const name = document.createElement('span'); name.textContent = c.n; const key = document.createElement('small'); key.textContent = c.k || ''; b.append(name, key); b.addEventListener('click', () => { modal.close(); c.a(); }); list.append(b); }); }; input.addEventListener('input', draw); draw(); input.focus(); }
  toast(message) { this.root.querySelector('.toast')?.remove(); const toast = document.createElement('div'); toast.className = 'toast'; toast.setAttribute('role', 'status'); toast.textContent = message; this.root.append(toast); setTimeout(() => toast.remove(), 3000); }
}
